# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5de4a34cd9e8bfcdf5a4c9b094803d618631cc96634e6ef77ca3b3a1e7dbfbfaa8e637ffd79ce5ab5ac7dc7d11a2d2f3272ee9f13aac7051d172271d73613364

test:
  secret_key_base: 479439ebaf9dd7c2e2d3c80bdade73b62002d5326f14386087952b27f94a735984670c67fcbc1a8583d159c8e0c2209bb5e42e48972f58d4b43c8f601335417d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
